# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180607_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu2',
            name='sub_menu',
            field=models.ForeignKey(db_column='sub_menu_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.SubMenu', verbose_name='父菜单'),
        ),
    ]
