# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcar',
            options={},
        ),
        migrations.AddField(
            model_name='shopcar',
            name='order',
            field=models.ForeignKey(db_column='oid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Order', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='shopcar',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Shop', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.User', verbose_name='用户ID'),
        ),
        migrations.AlterModelTable(
            name='shopcar',
            table=None,
        ),
    ]
