# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180608_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
